### ISSUE TITLE
Design component in Figma

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#1012]
## What
Work alongside others in the team to create a design for the component and prepare in Figma for handover to development. Also, ready the design of the component in Figma to be released into the MoJ Figma Kit.

## Why
After the discovery phase, findings and insights have been found around the usage of the component. In collaboration with content, development, and accessibility, the design of the banner component needs to reflect the insights from discovery.

## Who needs to be involved
- Interaction Designer (Leading)
- Content Designer
- Developer
- Accessibility specialist

## Tasks
- [ ] 
- [ ] 

## Done
When the component is created on a branch of the MoJ Figma Kit in preparation for merging on release day.

**Comment by murrlipp** [comment]
This is now done and in a Figma branch here: https://www.figma.com/design/MhpA8RbhYwYpr40kUvi03S/banner?node-id=66-5802

Outstanding tasks to be done before the close of the cycle:
- [ ] Rename component and pages as necessary if renaming is decided upon
- [ ] 'Archive' old banner Figma component

Outstanding tasks to be done before releasing branch:
- [ ] Update 'last updated' date
- [ ] Update link to documentation site page
