### ISSUE TITLE
Write documentation for component

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#1013]
## What
- Develop the documentation for the banner component based on the insights found during discovery.
- Use the documentation template to guide the structure of the documentation.
- Use the MoJ Design System standards to guide the documentation, specifically using GOV/MoJ style guides.

## Why
- To help users understand how best to use the banner component.

## Who needs to be involved
- Content Designer

## Tasks

- [x] Draft guidance on documentation
- [x] Finalise first draft   
- [x] Get into Preview
- [x] Share with team, 2i and accessibility Ben at same time
- [x] process all feedback
- [ ] Finalise with team
- [ ] Produce content for associated components (to create journeys back to the banner)

**Comment by helennickols** [comment]
Naming conversation to integrate - https://mojdt.slack.com/archives/C07NAM5S7M0/p1737649889025409

**Comment by helennickols** [comment]
This is with 2i.
