### ISSUE TITLE
Improve: Button menu component

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#624]
## What
Improve the [Button Menu component](https://design-patterns.service.justice.gov.uk/components/button-menu) to meet the updated standards of the MoJ Design System.

## Why
To increase trust in the MoJ Design System and provide more robust, consistent, usable, and accessible components to users.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer

## Tasklist
- [x] Designers feedback on component
- [x] Develop survey
- [x] send out survey
- [x] Process survey results (from 12 Sept)
- [x] Talk through disco findings and discuss next steps (13 Sept)

**Comment by robertjmccarthy** [comment]
```[tasklist]
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task
```

**Comment by robertjmccarthy** [comment]
### Tasks

- [ ] #243
- [ ] #242
- [ ] Draft task

**Comment by helennickols** [comment]
- [ ] To do item 1 
- [ ] to do item 2
