### ISSUE TITLE
Finish documentation template

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#668]
## What
A new documentation template has been created and iteratively tested. This task is to finish the template so it's ready for build.

## Why
To accommodate a new documentation structure on the MoJ Design System guidance site, a new template has been created.

## Who needs to be involved
- Content Designer
- Interaction designer

## Tasks

- [x] Add accessibility banner to the template
- [x] Finish single page doc template
- [x] Finish tabbed template
- [x] Create a template in Figma for a tabbed version and another for a single page version
- [x] Work through [G doc list](https://docs.google.com/document/d/1kX5lEZu4zHFutNa8XFI7jK5R4sNGvosqoPfZzz0D56o/edit)
- [x] Fix Figma bug - M
- [x] Create a template in Google Docs for a single page version - H
- [x] Dev and documentation work - M&C
- [x] Add a documentation template page on Confluence (in the [Processes section](https://dsdmoj.atlassian.net/wiki/spaces/DO/pages/4974903336/Processes)) with links to Figma and Google Doc templates - H
- [x] Agree both with team - all

### After agreed with team 

- [x] Archive previous Figma versions so there's a single source of truth - M
- [x] Archive [documentation template page](https://dsdmoj.atlassian.net/l/cp/kUdQtYV6) on Confluence - H

**Comment by helennickols** [comment]
This isn't blocked but no work can happen on it until the team discussion on 16 sept, therefore I've moved it out of 'in progress'.

**Comment by helennickols** [comment]
I would say there are 2-3 hours more work on this at the most. This is processing feedback, building out the tabbed version and then adding to Confluence.

**Comment by helennickols** [comment]
I believe this is done - [Figma link](https://www.figma.com/design/CpTvAGL8rct5ugC8KWuXLz/Playground?node-id=2329-4520&node-type=frame&t=QtYJ38kVxq7bqQMg-0).

@robertjmccarthy you raised a good point about how to flag accessibility issues. The comment was:
```
Where would accessibility issues show on the page?
We wouldn’t go live with a component that has an accessibility issue, but if an issue was reported to us then we would want to update the page whilst we make and release an update.
```

Would you like me to do that in this version or the next one? @murrlipp would be needed as this strikes me as banner territory...

**Comment by robertjmccarthy** [comment]
@helennickols I've included a previous example of how we thought about displaying an accessibility issue that arises.

The idea came from Martin Glancy about telling people there was an issue as soon as we were aware, and then we can work on fixing it and releasing the fix. So the plan was to detail what the issue is, including a date we would have it fixed by, and include copy for an accessibility statement that teams could update on their product/service/website.

I've added [what was worked on before](https://www.figma.com/design/CpTvAGL8rct5ugC8KWuXLz/Playground?node-id=2927-11025&t=lGfCh7PFakOqG5Xc-1) next to the prototype you're working on.

I think it would be good to add it into this version. Chat with @murrlipp and decide if the earlier version of the accessibility issues would work as is, or if it needs some further work as a banner.

**Comment by helennickols** [comment]
Template is done pending sorting out the contributors heading stuff:
https://docs.google.com/document/d/1ZG_-KOFRlnqQlCwu0X9qqNALYnWXPRP-iS0C2g5reMU/edit#heading=h.bt969rkrvk1t

**Comment by robertjmccarthy** [comment]
@murrlipp

Couple of tasks now that the design is completed for the documentation template...

- [ ] Update the 'Contributors' and 'Help and feedback' section of the button menu component documentation (on staging) to reflect the design of the documentation template: https://www.figma.com/design/x4AH3waUFmb6SW9iC38CJ0/New-and-improved-building-blocks?node-id=42-7187&t=4bJ2QuRnll09ega8-1
- [ ] Apply the 'Help and feedback' section update to all component documentation pages on live.
- [ ] Update the 'Contributors' section and 'Help and feedback' section of the date picker component documentation (on live) to reflect the documentation template change.

**Comment by murrlipp** [comment]
@robertjmccarthy on the two last points above, I was planning on making these changes after the button menu updates have been merged into main, as it will be more straightforward.

I can make these changes to live first if it's helpful to get them done sooner, but it will create a little more work now.

**Comment by murrlipp** [comment]
Agreed on a call that we would create a separate task for the above points to take place in the next cycle, when button menu has been deployed.
