### ISSUE TITLE
Add interactions to GOV and MoJ Figma Kits

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#672]
## What
Add interactions (e.g. hover states) to the GOV and MoJ Figma Kits.

## Why
Figma is used to create prototypes, and interactions on components can enhance a user's experience when involved in a usability test. Adding interactions at a design system level will save time for individual Interaction Designers working across different prototypes.

## Who needs to be involved
- Interaction Designer

## Tasks
- [x] Audit interactions in both kits
- [x] Add missing interactions
- [ ] Document changes
- [ ] Publish changes
- [ ] Announce changes on [#moj-design-system-support](https://moj.enterprise.slack.com/archives/CH5RUSB27)
