### ISSUE TITLE
Add 'Task list' component to GOV Figma Kit

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#721]
## What
Add a component to the GOV Figma Kit for the [Task list](https://design-system.service.gov.uk/components/task-list/) component of the GOV uk design system.

## Why
There is no Figma component for this and it is likely to help designers work more quickly.

## Who needs to be involved
- Interaction Designer

## Tasks

- [x] Check playground for existing versions
- [x] Create component
- [ ] Fill out release notes
- [ ] Publish library changes with release notes
