### ISSUE TITLE
Add 'Password input' component to GOV Figma Kit

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#722]
## What
Add a component to the GOV Figma Kit for the [Password input](https://design-system.service.gov.uk/components/password-input/) component of the GOV uk design system.

## Why
There is no Figma component for this and it is likely to help designers work more quickly.

## Who needs to be involved
- Interaction Designer

## Tasks
- [ ] Check playground for existing versions
- [x] Create component
- [ ] Fill out release notes
- [ ] Publish library changes with release notes

**Comment by murrlipp** [comment]
Is it worth waiting until we look into the MOJ's 'password reveal' component in case of duplication/succession?
