### ISSUE TITLE
Documentation written for component

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#760]
## What
- Update documentation for the [button menu component](https://design-patterns.service.justice.gov.uk/components/button-menu/) based on the insights found during discovery.
- Use the documentation template to guide the structure of the documentation.
- Use the MoJ Design System standards to guide the documentation, specifically using GOV/MoJ style guides.

## Why
- To help users understand how best to use the Button menu component.
- - To update the guidance of the component to the MoJ Design System standard.

## Who needs to be involved
- Content Designer

## Tasks

- [x] Draft guidance on documentation - [G doc](https://docs.google.com/document/d/1Jt9BmuKo4-hXyvy9yHlcylSmfuj4DZ4wfyNuKwVTrhY/edit#heading=h.4e2fhfnm4oe2). 
- [x] Decide on title - button menu or menu button
- [x] Resolve comments 
- [x] Finalise first draft on Mon 30 Sept
- [x] Share with accessibility Ben
- [x] Add relevant examples
- [x] Work through [Google doc changes](https://docs.google.com/document/d/1kX5lEZu4zHFutNa8XFI7jK5R4sNGvosqoPfZzz0D56o/edit)
- [x] Do feedback from 8 Oct - [Google doc](https://docs.google.com/document/d/1HJbJArKaYHQUHt4bBmGHuvb0Hq2aX6NS93MMUoGCxkw/edit)
- [x] Send to 2i for final review
- [x] Process tiny 2i changes
- [x] Assess if changes needed to the documentation after component build
- [x] Change the Help page
- [x] Finalise with team

**Comment by helennickols** [comment]
Proposing that we may be able to release this on Mon 7 October

**Comment by helennickols** [comment]
In blocked because waiting on some code changes and alt text review
