### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#775]
## What
An Accessibility Specialist will be part of the building block improvement work. But, a final review the building block against WCAG 2.2 criteria is to be completed.

## Why
As part of the MoJ Design System standard, all building blocks within the design system must be WCAG 2.2. compliant.

## Who needs to be involved
- Accessibility Specialist
- Interaction Designer
- Content Designer
- Developer

## Done
When an MoJ Accessibility Specialist confirms the building block is WCAG 2.2 compliant.

## Tasks

- [ ] Meeting with Ben for initial overview
- [ ] Ben looking through guidance
- [ ] Accessibility review of component once built 
- [ ] Accessibility review of documentation once finished
