### ISSUE TITLE
Complete release checklist

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#776]
## Pre-release checklist
- [ ] Content: write content for What’s new section of documentation website
- [ ] Content: write Slack post
- [ ] Content: write MoJ FE release note
- [ ] Content: write Figma release note
- [ ] Content: write Notify content
- [ ] Team: agree Slack post, Notify email and release notes

## Decision point
- [ ] Team decision point: is the release ready?

## Release checklist
- [ ] Developer: Commit the changes to MoJ FE
- [ ] Developer: Publish changes from staging to documentation site (inc. release notes)
- [ ] Team: Check published version on a call (to start no later than 3pm on day of release)
- [ ] Interaction: Merge component branch to main MoJ Figma Kit
- [ ] Interaction: Publish update on Figma (inc. release notes)
- [ ] Developer: Commit homepage content
- [ ] Content: Send Slack post
- [ ] Content: Send Notify email

## Post-release checklist
- [ ] Lead: Create discussion on Github for released component
- [ ] Lead: Add building block to analytics spreadsheet
- [ ] Lead: Check [accessibility audit report](https://docs.google.com/spreadsheets/d/1kDDGoBK0RvPvPPsffIvo1GuNJK8BkWxRPWiuOS3C4Qs/edit?usp=sharing) for any existing component issues and reach out to teams to consider using the released one
