### ISSUE TITLE
Add 'Add another' component to MoJ Figma Kit

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#817]
## What
Add a component to the MoJ Figma Kit for the [Add another](https://design-patterns.service.justice.gov.uk/components/add-another/) component of the MoJ design system.

## Why
There is no Figma component for this and it is likely to help designers work more quickly.

## Who needs to be involved
- Interaction Designer

## Tasks
- [ ] Check playground for existing versions
- [ ] Create component
- [ ] Fill out release notes
- [ ] Publish library changes with release notes
- [ ] Add link to Figma component to live documentation site

**Comment by Whersi** [comment]
@murrlipp Was just going through the coded example box and I realised this component doesn't have a figma tab on staging.

**Comment by murrlipp** [comment]
I did add it but it looks like it's been lost, maybe in a rebasing error.  Could you reopen the ticket please and I'll add it at some point?

**Comment by murrlipp** [comment]
Awaiting PR review
