### ISSUE TITLE
Add 'Messages' component to MoJ Figma Kit

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#819]
## What
Add a component to the MoJ Figma Kit for the [Messages](https://design-patterns.service.justice.gov.uk/components/messages/) component of the MoJ design system.

## Why
There is no Figma component for this and it is likely to help designers work more quickly.

## Who needs to be involved
- Interaction Designer

## Tasks
- [x] Check playground for existing versions
- [x] Create component
- [x] Fill out release notes
- [x] Publish library changes with release notes
