### ISSUE TITLE
Add 'Sortable table' component to MoJ Figma Kit

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#821]
## What
Add a component to the MoJ Figma Kit for the [Sortable table](https://design-patterns.service.justice.gov.uk/components/sortable-table/) component of the MoJ design system.

## Why
There is no Figma component for this and it is likely to help designers work more quickly.

## Who needs to be involved
- Interaction Designer

## Tasks
- [x] Check playground for existing versions
- [x] Create component
- [ ] Fill out release notes
- [ ] Publish library changes with release notes
- [ ] Add link to Figma component to live documentation site
