### ISSUE TITLE
Update 'Get help and contribute' section and Figma tab wording across all pages

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#848]
## What
The 'Get help and contribute' section was updated during the updates to the button menu component. This was made as a local change and the update needs to be made to all component, pattern and page pages on the design system site.

## Why
For a consistent experience between different pages.

## Who needs to be involved
- Interaction Designer
- Content Designer

## Tasks
- [x] Make changes to nunjucks partial
- [x] Account for instances where there are no contributors
- [x] Remove template from index pages and archived component pages
- [x] Make changes to 'Figma' component tab wording - liaise with @helennickols 
- [x] Once button menu changes are deployed, create PR
- [x] PR reviewed

## Done
Add info about what this task looks like when it's done.

**Comment by murrlipp** [comment]
The branch for this work is here: https://github.com/ministryofjustice/moj-frontend/tree/help-and-feedback-changes

Once the button menu branch is merged to main I'll pull down, check, and create a PR.
