### ISSUE TITLE
Write documentation for component

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#850]
## What
- Develop the documentation for the Interruption card based on the insights found during discovery.
- Use the documentation template to guide the structure of the documentation.
- Use the MoJ Design System standards to guide the documentation, specifically using GOV/MoJ style guides.

## Why
- To help users understand how best to use the Interruption card component.

## Who needs to be involved
- Content Designer

## Tasks

- [x] Draft guidance on documentation
- [x] Resolve comments 
- [x] Finalise first draft   
- [x] Get into Staging
- [x] Share with team, 2i and accessibility Ben at same time
- [x] process team feedback
- [x] Process 2i changes
- [x] process accessibility changes
- [x] Graham feedback
- [x] Other 2i feedback
- [x] Survey responses
- [ ] Finalise with team

**Comment by helennickols** [comment]
@KiahMadz Are you OK to glance over [my survey analysis? ](https://miro.com/app/board/uXjVLRrn_OE=/?moveToWidget=3458764609211157831&cot=14) I think it's all pretty doable (and helpful!) 
Thank you for running it for me, queen.

**Comment by KiahMadz** [comment]
> [@KiahMadz](https://github.com/KiahMadz) Are you OK to glance over [my survey analysis? ](https://miro.com/app/board/uXjVLRrn_OE=/?moveToWidget=3458764609211157831&cot=14) I think it's all pretty doable (and helpful!) Thank you for running it for me, queen.

Done. Fed back to Helen via Slack conversation as follows:

**Comment by robertjmccarthy** [comment]
@helennickols and @KiahMadz - just noting the points about there being a lot of information on the page. We do have the new documentation template which John is going to start working on. The plan will be to apply this to new components like this Interruption card component. And, the purpose of the tabbed documentation template is to help make the content more digestible.

Flagging as you may want to leave this insight for solving by using the tabbed documentation template.

**Comment by helennickols** [comment]
Guidance is now with the team for review. This will move out of blocked by Monday morning.
