### ISSUE TITLE
Define scope of the new component

### ISSUE THREAD

**Issue by helennickols** [ministryofjustice/moj-frontend#908]
## What
The IC discovery is completed. There's some work to do to define the IC before work begins. This is defining what the build is and what will be covered in documentation.

## Why
- To help users understand how best to use the Interruption card component.
- To ensure that the team is aligned on what it's working towards

## Who needs to be involved
- IxD
- FE dev
- Content Designer

## Tasks

- [x] team meet on 8 Nov to finalise the scope
- [x] It's documented

**Comment by helennickols** [comment]
hey @Whersi - this is the card we discussed in stand-up.

**Comment by helennickols** [comment]
@murrlipp I think we only need 30 mins to confirm this on Friday. Perhaps we could use the rest of the time to look at the guidance together. :-)

**Comment by murrlipp** [comment]
Scope agreed between @helennickols, @chrispymm and @murrlipp for Interruption card v1:

# v1

## Component

- [ ] Must be used alone on a page between header and footer, with no other content on the page.
- [ ] The user must interact with the component to move on in the journey.
- [ ] Must have a heading, body content and at least 1 CTA, with a maximum of 2 CTAs.
- [ ] Must always be presented at full width (over 3 columns) with content spanning 2/3 columns within for readability.
- [ ] If 2 CTAs are used, they should be along the lines of 'continue' and 'go back and change something'.
- [ ]  No minimum height.
- [ ] No build constraint on maximum height. Guidance to help users understand how much content is too much, which would affect the height of the component.
- [ ] Above points mean that component cannot be used as a banner, or a means of emphasising a heading.

## Guidance

- [ ] Three main use cases will be recommended in guidance, which will in turn help users decide on success metrics:
  - [ ] Complex, non-contextual error messages, and an ‘are you sure?’ pattern 
  - [ ] Application outcomes which are not a straightforward yes or no
  - [ ] Presenting important content to users before they do a task, particularly if that content was elsewhere and being missed
- [ ] Suggest considering a different journey if an interruption is needed alongside other content.
- [ ] Suggesting considering whether the IC is necessary, if you are deciding to use it NOT as a result of testing insight
- [ ] Suggest a general design steer if people are in a service where lots of ICs are emerging (similar to guidance on button menus becoming very long)
- [ ] Link to alternative components where appropriate (task list, banner, etc.)
- [ ] Any guidance about overuse and overexposure should help users consider their use, rather than dictate a limit
- [ ] Any instructions about using the component to have a user 'agree' to something to be in line with GOV.UK guidance on declarations
- [ ] Specify that this component is for high impact interruptions.
- [ ] Call out that the DS Team do not understand the impact of including images in the interruption card at the moment.
- [ ] Call out that there may be other use cases and we'd like to hear about them.
- [ ] Avoid implying that the component is for 'emphasis' to ensure users do not misuse it as such.


# v2

- [ ] Explore support for more than 2 CTAs.
- [ ] Explore support for image/illustrations.
- [ ] Explore an 'interruption pattern' which would advise on how, when and why to interrupt users.
- [ ] Evaluate from other discoveries whether there is a need to add to the documentation examples of where a component has been used in a live service.
