### ISSUE TITLE
GOV Figma Kit updates for GOV.UK Frontend v5.7.0

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#918]
## What
Following the review of the GOV.UK Frontend v5.7.0 we are required to update the GOV.UK Figma kit.

## Why
So users have the most upto date GOV.UK Figma kit.

## Who needs to be involved
- Interaction Designer

## Tasks

- [x] Update spacing on GOV.UK Service navigation component: https://github.com/alphagov/govuk-frontend/pull/5278
- [ ] Update spacing on GOV.UK Details component: https://github.com/alphagov/govuk-frontend/pull/5352
- [x] Fill out release notes
- [x] Publish library changes with release notes

**Comment by murrlipp** [comment]
This is complete. Noting here that no changes were required to the 'Details' component as the spacing was already collapsed.
