### ISSUE TITLE
Investigate whether visitors to documentation site would benefit from example iframe changes

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#933]
## What
Investigate what the most common screen resolutions are of visitors to the MoJ Design System documentation website, to see whether or not it would be valuable to adjust the width and height of the example iframes on component pages.

## Why
We are advising that some components, such as the 'Interruption card', should be used at certain widths in services.  In some cases, the width we recommend is larger than the width of the iframe on the documentation site.  The component is responsively resized to fit within the iframe, but this may give users an incorrect idea of how the component should or will look in their service.

Additionally, the iframes only accept one height value.  Where responsive components have vastly different heights between desktop and mobile, this can lead to the mobile view having lots of white space underneath the component. This may be negatively affecting mobile visitors experience.

## Who needs to be involved
- Interaction Designer

## Tasks
- [x] Check Google Analytics for screen resolution and device data
- [x] Understand what percentage of users are affected
- [x] Document findings and recommendations
- [ ] Communicate to MoJ Design System team

## Done
This task is done when findings and recommendations have been documented and communicated to the wider team.

**Comment by murrlipp** [comment]
@robertjmccarthy summary of the relevant GA visitor data below against the hypotheses, if you have time to read.  I'm also happy to discuss on a call if you'd prefer.  I haven't made recommendations here.

---

## Increasing the width of the example iframe (or all page body content)

### Hypothesis
Increasing the width of the example iframe from 840px to 1080px would allow us to represent 'full width' components (e.g. interruption card, banner, identity bar, etc.) at 1020px within the iframe, which is the [default maximum page width recommended by GDS](https://design-system.service.gov.uk/styles/layout/#:~:text=The%20default%20maximum%20page%20width%20is%201020px%2C%20but%20you%20can%20make%20it%20wider%20if%20your%20content%20requires%20it.).

### Data
The example iframe is currently 840px wide, making the overall content of the page 1260px wide:
- 300px: side nav
- 60px: body content padding left
- 840px: body content / example iframe
- 60px: body content padding right

Increasing either the iframe width, or the body content width (including the iframe) from 840px to 1080px would increase overall width of the page content to 1500px.

According to Google Analytics, over the last 90 days:
- 848 of 934 (90.8%) of desktop users had resolution widths over 1260px
- 703 of 934 (75%) of desktop users had resolution widths over 1500px

### Summary
If we increase the width of our examples — or all body content — from 840px to 1080px, **75% of our users would see a better representation of what components would look like at the default maximum page width recommended by GDS**.  The remaining 25% would see responsive examples.

---

## Impact of white space underneath examples when viewed on mobile

### Hypothesis
Visitors to the documentation site on mobile devices are seeing white space underneath examples, and it contributes to a poor experience.

### Data
Over the last 90 days:
- 81 of 933 (8.7%) of our visitors are on a mobile device
- Visitors on mobile devices spend 80.8% less time on the documentation site that visitors on desktops

### Summary
Data shows that mobile users are not our primary user group. If we specify a separate iframe height for mobile users, **8.7% of our users would have a better experience viewing examples**.

**Comment by robertjmccarthy** [comment]
Thanks @murrlipp. A very comprehensive and data driven view.

I think the data suggests that it is worth increasing the width of the site. Could you create a ticket and add it to the backlog please?

I'm hesitant to progress the mobile device improvements as the percentage of users impacted would be low compared to adding javascript. Not that we shouldn't ever consider the use for progressive enhancement, but I'd be leaning to it not being of such importance to do here. What do you think?
