### ISSUE TITLE
Investigate MoJ IxD Figma user needs

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#935]
## What
We want to better understand the needs of Figma users within Justice Digital, so that we can improve the user experience of using the Figma libraries.

## Why
We have provided a basic level of support for Figma users by creating styles, colours and components within Figma, but we don't fully understand how designers and other colleagues across Justice Digital are using Figma and what their needs are.

## Who needs to be involved
- Interaction Designer
- Design System Lead

## Tasks
- [x] Get access to Dovetail
- [x] Review key insights previously documented in Dovetail
- [x] Design a workshop to collect insight about Figma use
- [x] Deliver the workshop in the Interaction Design CoP on 25th November 2024
- [x] Arrange 1:1 sessions with respondents if valuable (optional)
- [x] Carry out interviews
- [x] Synthesise results and make recommendations

## Done
This task is done when all of the above tasks (aside from those marked optional) are complete.

**Comment by murrlipp** [comment]
Moving to blocked as I'm waiting on a final interview that will happen on Monday 16th

**Comment by murrlipp** [comment]
Playback / conversation scheduled with @robertjmccarthy Friday 10th Jan.

**Comment by murrlipp** [comment]
@robertjmccarthy and I have had a debrief and the actions to go forward are, in priority order:

1. Add spacing to Figma libraries and socialise to Interaction Design community.
2. Write a 'benefits of using the design system' page, add to the DS site, with a link from the home page.
3. Write a page of guidance on how to choose the appropriate prototyping tool, and add to the DS site.

Not related solely to Figma:
4. Think about how we could gather common page designs (e.g. payments page, case management page, etc.) and standardise them into templates - note this is a long term goal to be added to the backlog and prioritised when appropriate.

Tickets for each to be added to the DS backlog.
