### ISSUE TITLE
Increase page body content on documentation site

### ISSUE THREAD

**Issue by murrlipp** [ministryofjustice/moj-frontend#936]
## What
As explored in https://github.com/ministryofjustice/moj-frontend/issues/933, increasing the width of the body content on the documentation site component, page and pattern pages would allow us to represent 'full width' components at 1020px within the iframe, which is the [default maximum page width recommended by GDS](https://design-system.service.gov.uk/styles/layout/#:~:text=The%20default%20maximum%20page%20width%20is%201020px%2C%20but%20you%20can%20make%20it%20wider%20if%20your%20content%20requires%20it.).

## Why
We are advising that some components, such as the 'Interruption card', should be used at certain widths in services. In some cases, the width we recommend is larger than the width of the iframe on the documentation site. The component is responsively resized to fit within the iframe, but this may give users an incorrect idea of how the component should or will look in their service.

## Who needs to be involved
- Interaction Designer
- Developer

## Tasks
- [ ] IxD and dev to discuss layout options - column spans vs fixed widths, etc.
- [ ] Width of body content to be updated
- [ ] PR created
- [ ] Code reviewed
- [ ] Merged into main

## Done
This task is done when the change is made, reviewed, and merged into main.
